version: "3.7"

services:
  # .NET 5.0 Backend Api
  api:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: erenkaya/digital-menu:api
    container_name: api
    ports:
      - 5001:80
    depends_on:
      - db
      - redis
      - rabbitmq
    restart: always
    environment:
      # production or development
      ASPNETCORE_ENVIRONMENT: development

      # Required
      # The url where REST API is running
      API_URL: http://api.digitalmenu-iesu.tk

      # Required
      # The url where Vue client app is running
      CLIENT_APP_URL: http://digitalmenu-iesu.tk

      # Optional
      # Default => Username=user;password=postgres;Database=digital_menu;host=localhost;port=5432;Pooling=True;
      POSTGRESQL_CONNECTION_STRING: Username=user;password=postgres;Database=digital_menu;host=db;port=5432;Pooling=True;

      # Optional
      # Default => 127.0.0.1
      REDIS_HOST: redis

      # Optional
      # Default => 6379
      REDIS_PORT: 6379

      # Optional
      # Default => localhost
      RABBITMQ_HOST: rabbitmq

      # Optional
      # Default => user
      RABBITMQ_USERNAME: user

      # Optional
      # Default => password
      RABBITMQ_PASSWORD: password

  # Vue Client App
  client:
    image: erenkaya/digital-menu:client
    container_name: client
    depends_on:
      - api
    ports:
      - 80:8080
    restart: always

  # PostgreSQL Db
  db:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
    volumes:
      - app-db:/var/lib/postgresql/data
    restart: always

  # Redis Cache
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    restart: always

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    restart: always

volumes:
  app-db:
